### ISSUE TITLE
loadc指令可以加载字符串吗？

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-vm-standards#2]
比如常量表如下

| index |  type  | value  |
| :---: | :----: | :----: |
|   0   | S | "hello world\n"  |
|   ...   | ... | ... |

loadc 0 加载的是？

**Comment by fazdzz** [comment]
可以，栈顶会是一个地址型的值，是那个字符串的首地址

**Comment by Zx55** [comment]
好的
