### ISSUE TITLE
一个无关紧要的勘误

### ISSUE THREAD

**Issue by LemonForeast** [BUAA-SE-Compiling/c0-vm-standards#3]
不是啥大问题，看到了顺手提醒一下
md文档中二进制文件o0格式这小节的struct Constant_info的注释里面的“根据type决定是String_innfo”猜测是多打了一个n吧，应该更正为“根据type决定是String_info”
https://github.com/BUAA-SE-Compiling/c0-vm-standards#%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6o0%E6%A0%BC%E5%BC%8F
关于md文档怎么permanent link不太会

**Comment by fazdzz** [comment]
的确，我键盘的n键可能是有点异物，最近经常按一下顶两下

另外建议issue的标题可读性好一点
