### ISSUE TITLE
函数嵌套的层级是什么意思？

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-vm-standards#4]
根据fun和main那个例子，显然不应该是调用的层级，因为level_fun = level_main + 1
那就是定义的层级？

可是c0的文法也不支持嵌套声明函数，所以只可能这里只可能是1？所以这个函数嵌套层级的意义是啥？

**Comment by fazdzz** [comment]
定义的层级，目前来看只可能是1

函数嵌套是被删减的内容，跟iaload之类的数组操作一样今年用不到了。

这学期过了之后会考虑要不要留着
