### ISSUE TITLE
loada指令在递归调用的函数中无法获取全局变量

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-vm-standards#5]
loada指令一个作用是获取当前栈帧上的地址loada 0, 1；另一个作用显然就是（也是唯一方法）为了获得全局变量所在栈栈的地址 loada $(函数调用链的长度), 0

对于无递归的程序，可以通过编译期跟踪调用链确定函数调用的层数；但是对于递归调用的函数，只有在运行时才能确定调用链的长度，显然对于递归函数无法通过操作数写死的loada指令来获取全局变量，这种情况该如何处理？

**Comment by Zx55** [comment]
PS：其实不理解loada指令的意义除了获取当前函数栈帧上的地址和全局栈帧上的地址外，还有什么其他作用？显然当前函数不可能去改变外层函数的栈帧，即使是指针参数也是通过地址间接修改的，直接操作外层函数的栈帧肯定是非法的

那为什么不将这个指令拆成两个指令，一个修改全局一个修改当前栈的

**Comment by fazdzz** [comment]
> loada指令在递归调用的函数中无法获取全局变量

是可以的，loada 的一个参数是沿 SL 链寻找，SL不是调用链，参考阅读：https://forum.lazymio.cn/t/241

> 那为什么不将这个指令拆成两个指令，一个修改全局一个修改当前栈的

所以说issue #4 提到了，本来是有函数嵌套的，我们降低难度给删了。现在在实验进行中进行这种大型改动不太合适，因为我们并不能估测有多少人已经写到了这个地步。

如果大部分人都觉得这里不太合适的话，那我们会去论证一下这里要不要立刻进行修改。

**Comment by Zx55** [comment]
哦哦 我好像明白了

也就是说对于c0中的函数
loada 1, operand2 都是全局栈帧的偏移地址
loada 0, operand2 都是当前函数的栈帧偏移

是不是这个意思？

**Comment by fazdzz** [comment]
> 也就是说对于c0
> loada 1, operand2 都是全局栈帧的偏移地址
> loada 0, operand2 都是当前函数的栈帧偏移

目前的确是这样的。唯一的例外是在 `.start` 里面使用时，只能 `load 0, offset`， 并且引用的是全局栈帧的地址。

**Comment by fazdzz** [comment]
另外如果您有更合理更完备的建议的话，也欢迎您给出一个完整的方案。我们是希望尽可能传递一个漏洞少一点的设计下去。

老师有提到明年的改革方向大概和LLVM，当前这个过渡用的VM不知道能不能用下去。

**Comment by Zx55** [comment]
好的，谢谢学长

PS：之前的确有想过用LLVM IR，这样最终的各种优化都由LLVM来处理，不过这学期实在精力有限 orz（特别是把软件设计从三下调整到三上简直是迷惑行为）

**Comment by fazdzz** [comment]
啊，如果老师说改革早一点的话，可能今年就改了，我们也是没这么多精力，才选的相对熟悉的栈式虚拟机去过渡
