### ISSUE TITLE
虚拟机指令说明中 size 的含义和规定不一致

### ISSUE THREAD

**Issue by yiranyyu** [BUAA-SE-Compiling/c0-vm-standards#7]
按照指令[说明](https://github.com/BUAA-SE-Compiling/c0-vm-standards/blame/82735f7255dbaa268e639ac5949ea473359fcf93/README.md#L707)和 [slot](https://github.com/BUAA-SE-Compiling/c0-vm-standards/blame/82735f7255dbaa268e639ac5949ea473359fcf93/README.md#L19) 的定义，括号内数字 ✖️ 4⃣️ 表示占用的字节数

> 格式： `opcode param1(size1), param2(size2)` (0x??)
> operand是操作数的名字，size是操作数占用的slot数

但是，在实际描述中出现了许多不一致的情况，下面给出其中很小一部分例子

1.  关于 `ipush value(4)`，[标准](https://github.com/BUAA-SE-Compiling/c0-vm-standards/blame/82735f7255dbaa268e639ac5949ea473359fcf93/README.md#L740)中提到 value 解释为 32 位有符号整数，那么应该占用一个 slot 而非 4 个，也就是说应该写作 `ipush value(1)`
2. 还有常用的 [`loada` 指令](https://github.com/BUAA-SE-Compiling/c0-vm-standards/blame/82735f7255dbaa268e639ac5949ea473359fcf93/README.md#L848) 也是将括号内的数字表示为字节数

我感觉是定义的时候写错了，指令里面的 size 应该是 bytes，栈中是 slots

**Comment by fazdzz** [comment]
没问题啊。。。。和指令写在一起的是param，在栈内的是operand

**Comment by yiranyyu** [comment]
> 没问题啊。。。。和指令写在一起的是param，在栈内的是operand

确实，我瞎了 orz
