### ISSUE TITLE
关于vm指导书排版的几点建议

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-vm-standards#8]
1. 指令集的总体索引在中间，每次找一条指令先要找到指令集的索引，然后才能定位到一条指令，可以尝试**把整个指令集的索引放在顶部**或者**把指令集的索引的索引放到顶部**

2. 中间举的这个实例也太长了，最好能**单独放在一个 example.md 里**或者干脆**放到最后**（就是这个太长，每次找指令集比较费劲）

3. 函数调用的过程比较重要，现在是套在 **虚拟机结构 / 运行时结构 / 栈** 里边，而且没有单独的标题，看的不仔细还容易看漏，建议**给函数调用单独立一级标题**

**Comment by fazdzz** [comment]
感谢建议，的确一个文档太长了很影响阅读体验，重构方式之后有空了会考虑

**Comment by Zx55** [comment]
可能在最顶部加上整个文档的索引体验会更好，但 github 的 markdown 似乎不支持 `[toc]` 语法

**Comment by fazdzz** [comment]
整合了部分同质指令的解释，暂时将示例移到了文末附录

**Comment by fazdzz** [comment]
增加了一个目录
